site_name: GeoSpot!
site_url: https://www.geospot.de/handbuch/
site_author: gb consite GmbH
site_description: Gebietsplanung, Whitespot-Analyse, Mediaplanung. Die GeoSpot! Geomarketing Plattform ist die modulare professionelle Location Intelligence App für Ihr Unternehmen.

nav:
    - Home: index.md
    - Whitespot-Analyse:
      - Übersicht: uebersicht-whitespotanalyse.md
      - Anwendungsbeispiele: anwendungsbeispiele-whitespot.md
      - Preise: preise-whitespot.md
    - Bezirksplaner:
      - Übersicht: uebersicht-bezirksplaner.md
      - Anwendungsbeispiele: anwendungsbeispiele-bezirksplaner.md
      - Preise: preise-bezirksplaner.md
    - Regio-Analyse:
      - Übersicht: uebersicht-regioanalyse.md
      - Anwendungsbeispiele: anwendungsbeispiele-regioanalyse.md
      - Preise: preise-regioanalyse.md
    - Mediaplaner:
      - Übersicht: uebersicht-mediaplaner.md
      - Aufbau: aufbau-mediaplaner.md
      - Grundlagen und Planungen: grundlagen-planungen-mediaplaner.md
      - Bearbeiten von Belegungen: bearbeiten-belegungen-mediaplaner.md
      - Datenimport: datenimport-mediaplaner.md
      - Preise: preise-mediaplaner.md
    - Blog:
      - blog/index.md
    - API:
      - GeoSpot! API: api-intro.md
      - Routen & Endpunkte: routen.md
      - Daten-Variablen: daten-variablen.md
    - Impressum: impressum.md
    - Datenschutz: datenschutz.md

theme:
  name: material
  custom_dir: docs/theme_override_home/
  # 404 page
  static_templates:
    - 404.html
  # enable light/dark mode
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # Don't include MkDocs' JavaScript
  include_search_page: true
  search_index_only: true
  # Default values, taken from mkdocs_theme.yml
  language: de
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - content.action.edit
    - content.code.copy
    - search.highlight
    - search.share
    - search.suggest
    
  font: false
  icon:  # from .icons path. Add to theme override for custom logo.
    logo: Lupe  # top left header logo
    repo: fontawesome/brands/git-alt
    edit: material/file-edit-outline
  favicon: assets/favicon.ico #browser tab logo

extra_javascript:
        - 'stylesheets/extra.js'
extra_css:
        - stylesheets/extra.css
        - stylesheets/font-awesome-4.7.0/css/font-awesome.min.css

repo_url: https://github.com/gbconsite/GeoSpot
repo_name: gbconsite/GeoSpot
edit_uri: ./edit/main/docs

markdown_extensions:
  - attr_list
  - md_in_html # enable lazy loading images via ![!](assets/Auftragsinfos.jpg){ loading=lazy }
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - markdown.extensions.toc:
      baselevel: 1
      permalink: ""
  - toc:
      title: Inhalt
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


plugins:
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
  - search:
      lang: de
  - glightbox
  - blog
  - social
  
extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/gb-consite-gmbh
    - icon: fontawesome/brands/xing
      link: https://www.xing.com/pages/gbconsitegmbh
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/gbconsite
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/standortanalyse
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Standortanalyse
      
#extra:
#  alternate:
#    - name: Deutsch
#      link: 
#      lang: de
#    - name: English
#      link: /en/ 
#      lang: en
